spring:
  boot:
    devtools:
      remote:
        debug: true

  mvc:
  #mvc설정
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
  #데이터 소스 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs1?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: user1
    password: skhuA+4.5
  security:
    oauth2.client:
      registration:
          google:
            client-id: 34791526453-u7cam5ju694g75dpssh8ao0avacvjuln.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: Jha_S6vXEH3mksPX5ysc
            client-secret: bGDH0tv745
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
      #provider설정
      provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
server:
  port: 8088
  
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
